version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/confd:/etc/mysql/conf.d
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      USER: "root"
      PASSWORD: "password"